### ISSUE TITLE
CommonJS support for sharer.js

### ISSUE THREAD

**Issue by okmttdhr** [okmttdhr/sharer.npm.js#1]
https://github.com/ellisonleao/sharer.js/issues/12
https://github.com/ellisonleao/sharer.js/issues/16

create https://github.com/okmttdhr/sharer.npm.js to support CommonJS

**Comment by ellisonleao** [comment]
Nice one! Thanks for that!

**Comment by okmttdhr** [comment]
Thanks for adding this on Readme🙇
